version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: ruby:2.4-alpine
    steps:
      - run: apk add --no-cache --update git ssh
      - checkout
      - run: bundle install
